#!/bin/bash

# assign variables
ACTION=${1}
VERSION=1.0.1

function show_version() {
echo "$VERSION"
}

function delete_file() {

rm "${1}-12345"

}

function create_file() {

touch "${1}-12345"
}


function display_help() {

cat << EOF
Usage: ${0} {-v|--version|-d|--delete|-c|--create|-h|--help} <filename>

OPTIONS:	
	-d | --delete	remove a specified file
	-v | --version 	Display script version
 	-c | --create	create a new file
	-h | --help	Display the command help

Examples:
	Delete a file:
		$ ${0} -d foo.txt
	Display script version:
		$ ${0} -v
	Create a new file:
		$ ${0} -c foo.txt
	Display help:
		$ ${0} -h
EOF
}

case "$ACTION" in
	-v|--version)
		show_version
		;;
	-d|--delete)
		delete_file "${2:-server}"
		;;
	-h|--help)
		display_help
		;;
	-c|--create)
		create_file "${2:-server}"
		;;
	*)
	echo "Usage ${0} {-h}"
	exit 1
esac
